Sabas merge
osmlab/onosm.org pull request #105
Opened 2022-12-22 06:58 UTC by ArcaneDots

Site seems to be working.  Translations should be complete but are rough. Plan to reduce number of translation keys used once this is PR is merged.

2023-01-15 17:58 UTC, ArcaneDots commented
Fully merged improvements from the Sabas fork back into main project. Fixed a few bugs and verified that notes were generated correctly.

2023-01-15 18:03 UTC, ArcaneDots commented
The Sabas fork already had fixes for issues #46 and #47

2023-01-16 00:24 UTC, iandees requested changes
Thanks for taking the time to do this.

Can you please fix a couple things for me:
* The CNAME, LICENSE, and README.md files should not be marked executable
* The CNAME file should stay at onosm.org otherwise the site will stop working

2023-01-16 00:24 UTC, iandees commented on CNAME
> +su.openstreetmap.it
Please don't change the CNAME.

2023-01-16 04:53 UTC, ArcaneDots commented on CNAME
> +su.openstreetmap.it
Must have missed these during the merge

2023-01-16 21:29 UTC, iandees approved these changes
Thanks!

2023-01-16 21:29 UTC, merged